name: "runnersui"
description: "runners ui"
version: "0.0.4"
slug: "runnersui"
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
startup: system
ports:
  4200/tcp: 4200
ingress: true
ingress_port: 4200
