name: "p1monitor"
description: "p1 monitor"
version: "0.0.12"
slug: "p1monitor"
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
startup: system
ports:
  8080/tcp: 8080
devices:
- /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI02DX1X-if00-port0
